# MongoDB Atlas Connection String
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb+srv://Inventory:apnacollege@cluster0.dskqtu.mongodb.net/inventory?retryWrites=true&w=majority&appName=Cluster0}

# Application Port
server.port=${PORT:8080}

# JWT Secret Key
jwt.secret=${JWT_SECRET:5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Bill Path for PDF generation
inventory.billPath=${BILL_PATH:./bills/}
